### ISSUE TITLE
operand size override (push 0xd)

### ISSUE THREAD

**Issue by mrexodia** [keystone-engine/keystone#10]
`push 0xd` outputs `66 6A 0D` which is `push word 0xd` the correct output is `6A 0D` (push a dword)

**Comment by aquynh** [comment]
this is fixed now

```
$ kstool x32 "push 0xd"
push 0xd = [ 6a 0d ]

$ kstool x32 "push word 0xd"
push word 0xd = [ 66 6a 0d ]
```

**Comment by mrexodia** [comment]
Great!

**Comment by aquynh** [comment]
can you confirm all the other issues you reported? most of them are fixed
now.

**Comment by mrexodia** [comment]
Yes I will look at all of them as soon as possible. I added some more tests
to XEDParse that currently fail for various reasons. I believe they pass
Keystone.
