### ISSUE TITLE
blx thumb bug 

### ISSUE THREAD

**Issue by McLovi9** [keystone-engine/keystone#166]
arm thumb code from IDA:

```
0xF400048A FF F7 54 EE BLX 0xF4000134
```
Ks will output:
```
ks = Ks(KS_ARCH_ARM, KS_MODE_THUMB)
enc = ks.asm("BLX 0xF4000134", 0xF400048A )[0]

enc -> FF F7 52 EE
that's -> F400048A 018 FF F7 52 EE      BLX  0xF4000130
```

**Comment by aquynh** [comment]
this is similar to a testcase we have at https://github.com/keystone-engine/keystone/blob/master/suite/regress/arm_blx_rel_thumb.py. can you confirm this testcase? (you can directly run this Python script)

**Comment by McLovi9** [comment]
what do you mean by "confirm this testcase" ? The current test from arm_blx_rel_thumb.py works ok but this one will fail:

```
encoding, count = ks.asm(b"BLX 0xF4000134",addr=0xF400048A)
self.assertEqual(encoding, [ 0xFF, 0xF7, 0x54, 0xEE ])
```

**Comment by aquynh** [comment]
I mean to confirm that testcase is correct. Then i am wondering why it
works, but your case does nit.

Can you send a new testcase for your instruction?

**Comment by McLovi9** [comment]
No sure why it does not work correctly but rasm2 from radare2 also has problems with blx thumb.

```
~$ rasm2 -b 16 -a arm -o 0xFB00048A "blx 0xFB000134"
Invalid destination for blx
Invalid destination for blx
Invalid destination for blx
Cannot assemble 'blx 0xFB000134' at line 3 invalid
```

**Comment by aquynh** [comment]
We have now 2 very similar testcases for Thumb BLX, but only one is correct encoded. This is confused. Can you confirm both cases by a simple Unicorn script, so we know both are encoded as expected?

**Comment by McLovi9** [comment]
in my unicorn test they both correct

**Comment by aquynh** [comment]
for the record, can you post your Unicorn test here?

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by McLovi9** [comment]
works correctly, thanks!
