### ISSUE TITLE
docs/COMPILE doesn't mentions how to change PREFIX

### ISSUE THREAD

**Issue by radare** [keystone-engine/keystone#182]
neither DESTDIR, CFLAGS, LIBDIR or any other common compilation environment commonly used.

**Comment by aquynh** [comment]
this was explained here https://github.com/keystone-engine/keystone/issues/21. PR to update docs is welcome.

**Comment by aquynh** [comment]
addressed this in commit https://github.com/keystone-engine/keystone/commit/1d980a06d345e056731e6e6a276a3200bf5e646d, thanks.
