### ISSUE TITLE
"keystone-engine" package is not claimed on PyPI

### ISSUE THREAD

**Issue by zachriggle** [keystone-engine/keystone#195]
While I understand there is not currently a deployable package for `pip install keystone-engine`, currently this is open for registration and available for squatting.  I recommend that it gets registered quickly :-)

(Unfortunately, `keystone` by itself is already claimed.  Is `capstone-engine` claimed?)

**Comment by aquynh** [comment]
registered "keystone-engine" name, thanks!

we already have "capstone" package on PyPi for a long time.

**Comment by zachriggle** [comment]
Correct, but with the mixed naming, it may be useful to also get
"capstone-engine" etc to avoid squatting

**Comment by mrexodia** [comment]
Never trust `pip` :+1:

**Comment by aquynh** [comment]
Keystone is now available on PyPi in package "keystone-engine", so you can install it it:

    $ sudo pip install keystone-engine

NOTE: this also build & install the core, so CMake must be installed on your machine before you run the above command.

if you have any issues, please report. thanks.
