### ISSUE TITLE
SHR/SHL/SAL/SAR

### ISSUE THREAD

**Issue by fvrmatteo** [keystone-engine/keystone#201]
The following instructions (and maybe some more, I need to do more tests) are not assembled: SHR, SHL, SAL, SAR.

The tests are made using the utility "kstool": kstool x32 "shr eax, 1"

Examples tested on https://defuse.ca/online-x86-assembler.htm:
"SHR EAX, 1" should be assembled as "D1 E8".
"SHL DWORD PTR SS:[ESP], 2" should be assembled as "C1 24 24 02".
"SAR DWORD PTR SS:[0x10000000], 3" should be assembled as "36 C1 3D 00 00 00 10 03".

Let me know if you need more tests or information.

**Comment by aquynh** [comment]
could you send a PR to include these instructions in a testcase under suite/regress/ ?

**Comment by fvrmatteo** [comment]
Test added under suite/regress/. Please check it and let me know if it is correct.

**Comment by aquynh** [comment]
i am traveling now. will fix this by this weekend, thanks.

**Comment by mrexodia** [comment]
related to #103

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by fvrmatteo** [comment]
Confirmed fixed, thanks!
