### ISSUE TITLE
pip3 install error

### ISSUE THREAD

**Issue by techvoltage** [keystone-engine/keystone#203]
raise IOError('Could not build the egg.')

OSError: Could not build the egg.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/keystone

[pip.txt](https://github.com/keystone-engine/keystone/files/322812/pip.txt)

**Comment by aquynh** [comment]
this is because we registered the package on PyPi, but havent uploaded it yet. will do that after Keystone is more stable, thanks.

**Comment by aquynh** [comment]
Keystone is now available on PyPi in package "keystone-engine", so you can install it:

    $ sudo pip3 install keystone-engine

if you have any issues, please report. thanks.

**Comment by aquynh** [comment]
NOTE: this also build & install the core, so CMake must be installed on your machine before you run the above command.
