### ISSUE TITLE
Is this an error for python binding?

### ISSUE THREAD

**Issue by cherry-wb** [keystone-engine/keystone#205]
Hi!
when i try to asm code: shr rax,1; a error detected,but all right for shr rax,othernum;

the test code is:
from keystone import *
ks = Ks(KS_ARCH_X86,KS_MODE_64)
ks.asm("shr rax,1")
and the exception is:
    raise KsError(errno)
keystone.keystone.KsError: Invalid operand (KS_ERR_ASM_INVALIDOPERAND)

is this an error?

**Comment by aquynh** [comment]
Yes, this is a known issue. Will fix that soon.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by aquynh** [comment]
here is the output with `kstool`:

    $ kstool x64 "shr rax, 1"
    shr rax, 1 = [ 48 d1 e8 ]

fixed, thanks!
