### ISSUE TITLE
Push byte size problem

### ISSUE THREAD

**Issue by b3mb4m** [keystone-engine/keystone#211]
For my experinces, push a byte on intel systems its just 2 byte.1 byte for mnemonic and other byte for whats left -anohter byte-.Seems like buggy on keystone, ex;

    padhex = lambda x: "0"+hex(x)[2:] if len(hex(x)[2:]) != 2 else hex(x)[2:]
    def getbyteset(arch, mode, code, syntax=0):
        ks = Ks(arch, mode)
        if syntax != 0:
            ks.syntax = syntax
        encoding, count = ks.asm(code)
        return [padhex(x) for x in encoding]
    print getbyteset(KS_ARCH_X86, KS_MODE_32, "push byte +0x5")
    print getbyteset(KS_ARCH_X86, KS_MODE_32, "push byte +0x68")

//Output  : ['66', '6a', '05']
//Output  : ['66', '6a', '68']

edit : I thought it has auto detech system(if 32 also support 16, if 64 also 32,16 etc..).It would be great, isn't ?

**Comment by aquynh** [comment]
Why did you close?

**Comment by b3mb4m** [comment]
I just thought its problem, but now seems like normal keystone flow.Auto detecting system its completely different system so i want keep that for pull request or issue.
