### ISSUE TITLE
Specify starting address for kstool

### ISSUE THREAD

**Issue by brendabrandy** [keystone-engine/keystone#212]
I am trying out different bindings of keystone (command line, python and C) and I am using the command line version to optimize the speed of assembly. However, is there a way to specify the starting address in the command line version so that I can achieve relative addressing? Because the other two are very slow when compared to the kstool command. The command I use is:
```
cat myfile.txt | kstool arm
```

**Comment by aquynh** [comment]
can you extend kstool.cpp to support one more (optional) argument for address? pull request is welcome then, thanks.
