### ISSUE TITLE
jmp 0x33, 08

### ISSUE THREAD

**Issue by mrexodia** [keystone-engine/keystone#214]
I sent a pull request with a regression test. With this instruction keystone says that it assembled something, but the size of the output is 0.

**Comment by aquynh** [comment]
yes, this should return something like "invalid operand". thanks

**Comment by mrexodia** [comment]
I believe it's a valid instruction on 16 bits. See the referenced issue at
x64dbg

**Comment by aquynh** [comment]
do you mean "jmp 0x33:08", with "," replaced with ":" ?

**Comment by mrexodia** [comment]
Yep

**Comment by aquynh** [comment]
fixed now. the right instruction is `ljmp` for far jump. we also use `lcall` for far call.

```
$ kstool x16 "ljmp 0x30,0x8"
ERROR: failed on ks_asm() with count = 0, error = 'Invalid operand (KS_ERR_ASM_INVALIDOPERAND)' (code = 512)

$ kstool x16 "ljmp 0x30:0x8"
ljmp 0x30:0x8 = [ ea 08 00 30 00 ]
```
