### ISSUE TITLE
error found in LDR/STR instructions of ARM

### ISSUE THREAD

**Issue by brendabrandy** [keystone-engine/keystone#222]
I was using keystone to assemble little Endian ARM and it seems that keystone cannot assemble files that contain the following lines:
```
STREQB R2, [R4, R3]
STRNEB R2, [R3]
LDRCCB R3, [R2], #1 
```
And when the error was caught, it gave me the following:
```
Traceback (most recent call last):
  File "errorCatch.py", line 19, in <module>
    encoding, count = ks.asm(bytes(CODE,'UTF-8'))
  File "/usr/local/lib/python3.5/dist-packages/keystone/keystone.py", line 195, in asm
    raise KsError(errno)
keystone.keystone.KsError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "errorCatch.py", line 21, in <module>
    print ("ERROR: %s" %e)
TypeError: __str__ returned non-string (type bytes)
```

**Comment by aquynh** [comment]
this is because STREQB, STRNEB & LDRCCB are all considered invalid instructions

**Comment by aquynh** [comment]
for reference, please provide the encoding (expected output) of all the above instructions.

**Comment by aquynh** [comment]
see the output from `kstool`:

    $ kstool arm "STRBEQ R2, [R4, R3]; STRBNE R2, [R3]; LDRBCC R3, [R2], #1"
    STRBEQ R2, [R4, R3]; STRBNE R2, [R3]; LDRBCC R3, [R2], #1 = [ 03 20 c4 07 00 20 c3 15 01 30 d2 34 ]

you can see that Keystone uses ARM UAL syntax, so STREQB must be changed to STRBEQ, STRNEB to STRBNE, etc. 

your code uses old syntax, which Keystone does not support. therefore `kstool` reports error like:

    $ kstool arm "LDRCCB R3, [R2], #1"
    ERROR: failed on ks_asm() with count = 0, error = 'Invalid mnemonic (KS_ERR_ASM_MNEMONICFAIL)' (code = 514)

**Comment by aquynh** [comment]
btw, your script returns error like `TypeError: __str__ returned non-string (type bytes)`. is this from v0.9, or latest Github code?

**Comment by brendabrandy** [comment]
That is from v0.9 . And thanks for the explanation!

**Comment by aquynh** [comment]
the latest code from Github already fixed that problem on "TypeError: __str__ returned non-string (type bytes)".

closed, thanks.
