### ISSUE TITLE
can't loop symbol

### ISSUE THREAD

**Issue by lunixbochs** [keystone-engine/keystone#230]
```
from keystone import *
ks = Ks(KS_ARCH_X86, KS_MODE_32)
ks.asm('L2: nop; loop L2')
```
> KS_ERR_ASM_INVALIDOPERAND

**Comment by aquynh** [comment]
you are missing `;' after `L2:`.

please always provide expected output.

**Comment by lunixbochs** [comment]
Expect terrible bug reports from me until after DEFCON. I'm extremely tight on time and mostly filing these issues as a courtesy while I work around the problems in another way.

**Comment by aquynh** [comment]
fixed now.

```
$ kstool x32 "l2:; nop; loop l2"
l2:; nop; loop l2 = [ 90 e2 fd ]
```

**Comment by lunixbochs** [comment]
Confirmed, thanks!
