### ISSUE TITLE
Python bindings - fail to load the dynamic library.

### ISSUE THREAD

**Issue by Inf0Junki3** [keystone-engine/keystone#235]
**Environment:** Kali 2.0 (sana), 64-bit.
**Version:** 0.9.1-3.
**Source:** Tried installing by cloning from github, by following instructions for keystone and bindings. Also tried from pip.

With source: looks like keystone compiles to a static library rather than a shared object. Did the lazy thing and used the pip package to install instead.

The pip package also does a cmake, with -DBUILD_SHARED_LIBS=ON. It produces the .so library here:
/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/keystone/libkeystone.so

It is not one of the paths that keystone.py searches, so keystone throws an error saying that the library was not found.

**Workaround:** One can move the file, or create a symlink in 
/usr/local/lib/python2.7/dist-packages/keystone

**Workaround 2:** One can add the following code to search in this (admittedly strange) location:
if _found == False:  
    # last try: loading from python lib directory  
    _lib_path = "/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/"
    for _lib in _all_libs:  
        try:  
            _lib_file = join(_lib_path, 'keystone', _lib)  
            #print(">> 2: Trying to load %s" %_lib_file);  
            _ks = cdll.LoadLibrary(_lib_file)  
            _found = True  
            break  
        except OSError:  
            pass

**Workaround 3:** One can install keystone with -DBUILD_SHARED_LIBS=ON and then remove the \* and (system() == 'Darwin')\* condition in keystone.py, line 62. **Note:** I tested this on Kali, not on other systems. This is probably the most elegant way of proceeding.

Please note that, after some rummaging through the source code, I tried running _setup.py install_ from the bindings/python folder, since I saw that it included compiling the library as a shared object. Not sure why (yet), but this didn't work.

**Comment by aquynh** [comment]
from source you can compile & install shared lib with:

```
$ mkdir build
$ cd build
$ ../make-share.sh
$ sudo make install
```

**Comment by aquynh** [comment]
the workaround 2 is not good.

wondering why Kali linux installs the core at that strange directory  /usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/keystone/libkeystone.so. if you find out why, please share.

**Comment by d0lph1n98** [comment]
By creating a symlink to the correct library path did solve the missing library error in ubuntu 16.04.1 but there is another issue:

```
Traceback (most recent call last):
  File "/usr/local/bin/keystone", line 9, in <module>
    load_entry_point('Keystone==0.2.1', 'console_scripts', 'keystone')()
  File "/usr/local/lib/python2.7/dist-packages/keystone/scripts.py", line 55, in main
    return serve(parser, args)
  File "/usr/local/lib/python2.7/dist-packages/keystone/scripts.py", line 58, in serve
    from keystone.main import Keystone
ImportError: No module named main
```

**Comment by aquynh** [comment]
no, you should not create symlink. on Ubuntu 16.04, you just need to add `/usr/local/lib` to `/etc/ld.so.conf`, then run `sudo ldconfig`. this is documented in https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-NIX.md.

**Comment by d0lph1n98** [comment]
Even if i do so, i still get the traceback but in my case the `/usr/local/lib` is already defined in the `/etc/ld.so.conf`. The workaround is to change a few lines in script.py and main.py. Now it works.

**Comment by aquynh** [comment]
where are the scripts.py & main.py from??

**Comment by aquynh** [comment]
not sure what you are using, but we dont have such files in Keystone engine.

**Comment by d0lph1n98** [comment]
The script.py and main.py is from `/usr/local/lib/python2.7/dist-packages/keystone/`, directly taken from the traceback.

**Comment by aquynh** [comment]
But Keystone does not have these files.

**Comment by d0lph1n98** [comment]
@aquynh ah my mistake, the traceback was from other python package installed on my machine. The installation on ubuntu 16.04.1 is ok.
