### ISSUE TITLE
bl/blx label wrong in ARM

### ISSUE THREAD

**Issue by dmxcsnsbh** [keystone-engine/keystone#248]
➜  ~ cat wrong.py

``` python
from keystone import *
from capstone import *

ks = Ks(KS_ARCH_ARM, KS_MODE_ARM)
md = Cs(CS_ARCH_ARM, CS_MODE_ARM)

CODE = b"""
loop:
    sub r0, r0, r0
    sub r1, r1, r1
    bl  loop
"""

data, count = ks.asm(CODE)
INS = ''.join(map(chr, data))

for i in md.disasm(INS, 0x100):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

➜  ~ python wrong.py

```
0x100:  sub r0, r0, r0
0x104:  sub r1, r1, r1
0x108:  bl  #0x108
```

should be `bl  #0x100`?

**Comment by aquynh** [comment]
Would you mind sending in a pull req to put this testcase under https://github.com/keystone-engine/keystone/tree/master/suite/regress?

**Comment by aquynh** [comment]
fixed this issue for BL instruction now, so your testcase now passes. but you did not provide testcase for BLX, so please confirm if BLX no longer has this problem.

**Comment by dmxcsnsbh** [comment]
BL/BLX Label is correct now, but i find another similar problem. In thumb mode, BLX label is wrong, and yet BL label is correct.

➜  keystone cat wrong.py
```python
from keystone import *
from capstone import *

ks = Ks(KS_ARCH_ARM, KS_MODE_THUMB)
md = Cs(CS_ARCH_ARM, CS_MODE_THUMB)

CODE = b"""
    blx  func
    movs r0, #0
    movs r1, #1
func:
"""

data, count = ks.asm(CODE)
INS = ''.join(map(chr, data))

for i in md.disasm(INS, 0x100):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

➜  keystone python wrong.py
```
0x100:	blx	    #0x100
0x104:	movs	r0, #0
0x106:	movs	r1, #1
```

so should I provide three different testcase files for ARM bl/blx label and Thumb blx label? or put them in the same file and rename?

**Comment by aquynh** [comment]
Another file, plz.

**Comment by aquynh** [comment]
fixed, thanks.
