### ISSUE TITLE
Incorrect BL operand in generated assembly

### ISSUE THREAD

**Issue by shakamd** [keystone-engine/keystone#257]
I'm doing a simple test whereby I disassemble some code, assemble it using keystone and then disassemble that output to verify the disassembly is the same. It appears to be failing on some branch instructions.

```
from capstone import Cs, CS_ARCH_ARM, CS_MODE_LITTLE_ENDIAN
from keystone import Ks, KS_ARCH_ARM, KS_MODE_LITTLE_ENDIAN

CODE = b"\xF0\x47\x2D\xE9\x00\x40\xA0\xE1\x01\x00\xA0\xE1\x01\x60\xA0\xE1\xFF\x90\x02\xE2\x22\x74
\xA0\xE1\x16\x94\xFF\xEB"

md = Cs(CS_ARCH_ARM, CS_MODE_LITTLE_ENDIAN)
asm = ''
for i in md.disasm(CODE, 0x2f964):
     asm += i.mnemonic + ' ' + i.op_str + '\n'

print asm

ks = Ks(KS_ARCH_ARM, KS_MODE_LITTLE_ENDIAN)
encoding, count = ks.asm(asm, 0x2f964)

new_asm = ''
md = Cs(CS_ARCH_ARM, CS_MODE_LITTLE_ENDIAN)
for i in md.disasm(str(bytearray(encoding)), 0x2f964):
    new_asm += i.mnemonic + ' ' + i.op_str + '\n'

print new_asm
```

yields:

> 
> push {r4, r5, r6, r7, r8, sb, sl, lr}
> mov r4, r0
> mov r0, r1
> mov r6, r1
> and sb, r2, #0xff
> lsr r7, r2, #8
> bl #0x149dc
> 
> push {r4, r5, r6, r7, r8, sb, sl, lr}
> mov r4, r0
> mov r0, r1
> mov r6, r1
> and sb, r2, #0xff
> lsr r7, r2, #8
> bl #0x44354

I'm trying to understand why the operand to the BL instruction has changed.

**Comment by aquynh** [comment]
are you using the latest Keystone from Github? some bugs with branch instructions were fixed recently.

be sure to use the latest Capstone from Github as well.

**Comment by shakamd** [comment]
Hi Nguyen,

Yes, using the latest versions of both. The bug seems to be with keystone
however, as the disassembly is correct.

On Wed, Nov 16, 2016 at 12:14 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
the difference is in the last instruction. see the output from Capstone

```
$ cstool arm "\x16\x94\xFF\xEB"
0  1694ffeb  bl	#0xfffe5060
```

and Keystone

```
$ kstool arm "bl #0xfffe5060"
bl #0xfffe5060 = [ 16 94 ff eb ]
```

i dont see any difference.

**Comment by shakamd** [comment]
Yes, if you take the single instruction out and operate on it alone it works, however the branch target is no longer correct when done in a block of other instructions (as in the example above).

**Comment by aquynh** [comment]
can you try to see if this is also the issue with Keystone v0.9.1?

**Comment by shakamd** [comment]
Yes, I've tried with the 0.9.1 source archive from http://www.keystone-engine.org/download/ and also built a fresh version from the github (although KS_MODE_LITTLE_ENDIAN no longer worked, I had to use KS_MODE_ARM when creating the Ks object).

**Comment by aquynh** [comment]
can you create a testcase for this issue, and send a pull req to put it under https://github.com/keystone-engine/keystone/tree/master/suite/regress? (please keep the input for Keystone relevant & as small as possible)

**Comment by shakamd** [comment]
Added

**Comment by shakamd** [comment]
It appears to happen when you have an lsr instruction before the branch in a block of 3+ instructions.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by shakamd** [comment]
Works correctly now, thanks!

Offtopic question, were the KS_MODE LITTLE/BIG ENDIAN flags removed for creating the Ks object? Now I can only specify KS_MODE_ARM otherwise I get a KSMode error.

**Comment by aquynh** [comment]
Can you give all examples causing error?

**Comment by aquynh** [comment]
i dont see any issues.

```
$ python
Python 2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from keystone import *
>>> ks = Ks(KS_ARCH_ARM, KS_MODE_ARM | KS_MODE_LITTLE_ENDIAN)
>>> ks = Ks(KS_ARCH_ARM, KS_MODE_ARM | KS_MODE_BIG_ENDIAN)
>>> ks = Ks(KS_ARCH_ARM, KS_MODE_ARM)
>>>
>>> quit()
$ 
```

**Comment by shakamd** [comment]
Ah, my mistake. I didn't realize the flags had to be ORed with KS_MODE_ARM.

**Comment by aquynh** [comment]
You can also use "+" instead of "|", it is all the same.
