### ISSUE TITLE
cross compile with Android NDK under Windows 7

### ISSUE THREAD

**Issue by noword** [keystone-engine/keystone#263]
I used lastest version of NDK(r13b) and cmake(3.7.1), under Windows 7 64bits.
Run this command under directory 'build'.
`cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=[MY NDK PATH] -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles" ../
`
Then got this error:
```
CMake Error at llvm/cmake/modules/GetHostTriple.cmake:24 (message):
  Failed to execute D:/projects/proj/keystone/llvm/cmake/config.guess
Call Stack (most recent call first):
  llvm/cmake/config-ix.cmake:293 (get_host_triple)
  llvm/CMakeLists.txt:324 (include)
```

The problem was in llvm/cmake/modules/GetHostTriple.cmake.
I googled it, found this issue:
https://reviews.llvm.org/D22370
But I think their solution was not simple.
My solution is just change one line at line 11:
```
-  elseif( MINGW AND NOT MSYS )
+  elseif( (MINGW OR ANDROID) AND NOT MSYS )
```

**Comment by aquynh** [comment]
cool, would you please send a pull req for this?

**Comment by noword** [comment]
Pull req was sent.

**Comment by aquynh** [comment]
PR merged, thanks!
