### ISSUE TITLE
Python: Crashes when assembling jal instruction in MIPS

### ISSUE THREAD

**Issue by ldyeax** [keystone-engine/keystone#269]
This code reproduces it:

from keystone import *

ks = Ks(KS_ARCH_MIPS, KS_MODE_MIPS64)
ks.asm("jal 0xFF0")

The result is this:

`  File "C:\Python27\lib\site-packages\keystone\keystone.py", line 195, in asm
    status = _ks.ks_asm(self._ksh, string, addr, byref(encode), byref(encode_siz
e), byref(stat_count))
WindowsError: exception: access violation reading 0x0000000000000FF0`

The operand given to jal appears to be getting dereferenced.

**Comment by aquynh** [comment]
i dont get this error here. can you try again with the latest Github code?

```
$ cat test.py
#!/usr/bin/python

from keystone import *

ks = Ks(KS_ARCH_MIPS, KS_MODE_MIPS64)
encoding, count = ks.asm("jal 0xFF0")
print("encoding = %s" %(encoding))

$ python test.py
encoding = [252, 3, 0, 12, 0, 0, 0, 0]
```

you can also confirm with `kstool`:

```
$ kstool mips64 "jal 0xff0"
jal 0xff0 = [ fc 03 00 0c 00 00 00 00 ]
```

**Comment by ldyeax** [comment]
I just built the latest github code and tried kstool. The newly compild kstool crashes when I try to assemble a JAL with it, same as the kstool available on the downloads page did. What environment did you build that on?

**Comment by aquynh** [comment]
i am on MacOS 10.12.2

**Comment by ldyeax** [comment]
I tried compiling on Debian 8.5 to see if it was a Windows issue. 

$ ./kstool mips64 "jal 0xff0"
kstool: /home/user/keystone/llvm/include/llvm/MC/MCInst.h:93: const llvm::MCExpr* llvm::MCOperand::getExpr() const: Assertion `isExpr() && "This is not an expression"' failed.
Aborted

Tried it with other mips expressions and it worked, just had the issue on this instruction.

It doesn't crash if I use something like "firstlabel: nop; jal firstlabel;" . The problem seems to be just with trying to use a raw address value for JAL, like the output of capstone gives.

**Comment by aquynh** [comment]
confirmed on Ubuntu 16.04, 64bit. can you send a pull request with this testcase & put it under https://github.com/keystone-engine/keystone/tree/master/suite/regress?

**Comment by ldyeax** [comment]
I've sent a pull request now

**Comment by xiaohuajiao** [comment]
Is this bug fixed by now? The latest version cloned from github seems still have this bug...

**Comment by aquynh** [comment]
not yet. will do when i have more free time. 
or you can beat me by trying to fix it.

**Comment by xiaohuajiao** [comment]
and submit a pull request, pls check...

**Comment by aquynh** [comment]
fixed now in the latest Github code thanks to the nice pull req of @xiaohuajiao. let me know if you still have issues.
