### ISSUE TITLE
Gem dependency of ruby binding

### ISSUE THREAD

**Issue by david942j** [keystone-engine/keystone#275]
Hi,
we are developing an open source project [pwntools-ruby](https://github.com/peter50216/pwntools-ruby/) and want use the keystone ruby binding as dependency.

While there's no available gem on rubygems, the way we know is to write a shell script to clone this repo, build the gem and install it.

Is there easier (and cleaner) way to add dependency?

Or, another way is to create a repo that contains bindings/ruby only then we can add dependency with source path.

Thanks.

**Comment by aquynh** [comment]
@sashs, the author of Ruby binding may have some comments here.

at the same time, if you think the Ruby binding can be improved, please send pull req.

**Comment by david942j** [comment]
Hi, any update :) ?

**Comment by sashs** [comment]
Hi. Sorry for the delay. I am still very busy and because I am not an ruby export I have to check the possibilities. Maybe someone other can help you. :)

**Comment by aquynh** [comment]
thank you for your time, @sashs! hopefully some Ruby experts will join this discussion soon.

**Comment by david942j** [comment]
In my opinion we can create a independent repository for ruby-binding (i.e. the gem).
Same as capstone does? (the crabstone gem)

**Comment by david942j** [comment]
need help >_<

**Comment by sashs** [comment]
This week I have a little bit time. If you can await until the end of the week, I will look at your problem.

**Comment by david942j** [comment]
And, can you provide a FFI-based ruby-binding?
In pwntools-ruby we don't want to force users installing the keystone/capstone core unless they are going to use asm/disasm features.
If ruby-binding using FFI, then it can shown a proper installation guide when `require 'keystone'`.

Sorry for keeping disturbing :cry:

**Comment by sashs** [comment]
Hey, sorry for the late response.
I will implement one, only for you. ;)

**Comment by david942j** [comment]
You are so nice!

**Comment by sashs** [comment]
Hey,
you can find a the ffi ruby bindings here https://github.com/sashs/ruby-keystone

**Comment by aquynh** [comment]
fantastic, do you want to get this merged to the current Ruby binding?

**Comment by sashs** [comment]
I think the cleaner way is to leave it outside, because there is still ruby bindings in this repo.

**Comment by aquynh** [comment]
ok i see

**Comment by sashs** [comment]
Whenthe ffi binding is used a lot, I will merge it to the keystone repo as well.

**Comment by david942j** [comment]
Tested in our project, works very well :D

**Comment by david942j** [comment]
For others' come to this page:
specify this in your Gemfile :D
```ruby
git 'https://github.com/sashs/ruby-keystone.git' do
  gem 'keystone'
end
```

**Comment by sashs** [comment]
But remember that you have to install unicorn separately. ;)

**Comment by aquynh** [comment]
why install unicorn? is that a typo?

**Comment by sashs** [comment]
:-D Yes, I thought of unicorn. I meant keystone. Sorry. ;-)

**Comment by aquynh** [comment]
btw, here is a Ruby gem (i dont know its status, though)

https://github.com/zachweed/rassembler/tree/master/keystone_gem

**Comment by sashs** [comment]
@aquynh  have you seen this file?
https://github.com/zachweed/rassembler/blob/master/keystone_gem/keystone.gemspec

It seems to be the ruby binding that is in the keystone repo

**Comment by aquynh** [comment]
Cool, i did not look inside it :-)

**Comment by sashs** [comment]
I do not know why he created an repository and put the files there. At the first look they seem to be exactly the same. 
The bindings that are here in the repo are also a ruby gem and also this one https://github.com/sashs/ruby-keystone. ;)
