### ISSUE TITLE
ARM64 branch instruction

### ISSUE THREAD

**Issue by noword** [keystone-engine/keystone#279]
I test with cstool(capstone):
`cstool  arm64 02000094 0x123456780

123456780  02000094  bl #0x123456788`

It works perfect.

Then I use kstool:
`kstool.exe arm64 "bl #0x123456788" 0x123456780

ERROR: failed on ks_asm() with count = 0, error = 'Unknow error' (code = 539)`

Maybe the start address is bigger then 0xffffffff (32bits limit), it caused this problem.

**Comment by noword** [comment]
I spent one night, track and run, finally I figured it out.
In llvm\lib\Target\AArch64\AsmParser\AArch64AsmParser.cpp line 773:
`    return (Val >= -(0x2000000 << 2) && Val <= (0x1ffffff << 2));`
It seems like that llvm limit the imm value of 'BranchTarget26'.
Is it a bug or a feature?

**Comment by aquynh** [comment]
Looks like a bug. Could you send a pull req to fix this?

**Comment by noword** [comment]
I pull the patch.
But if this is a bug, it's a bug of llvm, right?

**Comment by aquynh** [comment]
i think that is because of the way LLVM handle branch instruction: it does not let you specify offset address (0x123456780 in this case), like Keystone does.

**Comment by Roguebantha** [comment]
Just discovered this issue myself. Rather bothersome this one. Is there a solution for this issue, or is it just an outstanding "This isn't fixable because LLVM?"

**Comment by trevor403** [comment]
I am currently having this issue with PPC32
