### ISSUE TITLE
ARM64 ldr with PC-relative offset

### ISSUE THREAD

**Issue by noword** [keystone-engine/keystone#284]
`cstool.exe arm64 40000058 0x1234`
>1234  40000058  ldr     x0, #0x123c

`kstool.exe arm64 "ldr x0, #0x123c" 0x1234`
>ldr x0, #0x123c = [ e0 91 00 58 ]

I think that the result of capstone is right,  and it's a bug of keystone.
Am I right?

About the LDR (literal) instruction:
[http://infocenter.arm.com/help/topic/com.arm.doc.dui0802b/LDR_lit_gen.html](url)

**Comment by aquynh** [comment]
yes, the output of Keystone is based on offset 0, so it does not take the offset 0x1234 into account.

so yes Keystone is wrong on PC-relative offset in this case. if you can fix it, please do PR.
