### ISSUE TITLE
Got error when compile

### ISSUE THREAD

**Issue by Leeericent** [keystone-engine/keystone#311]
I have tried two ways to install keystone. First I use `sudo pip install keystone-engine` and got this error in the first picture below. Then I follows the `compile.md` to compile&install, I get the same error as former.
I'm working on Ubuntu16.4.
Dont know how to solve the program. Please help!
![error](https://www.evernote.com/shard/s717/sh/d2545e7f-f71c-4414-add3-d72eadb6563d/d84b5cd7e40eb5bf/res/fffc8b56-2dc6-4205-ba81-bec3019cdd18/skitch.png?resizeSmall&width=832)
Below is the output install with `../make-share.sh`
![error](https://www.evernote.com/shard/s717/sh/b551851f-eb93-4a1b-8290-18c199b4f2fe/6a20ad771f68ad90/res/38c5fdbd-e673-4993-a0b7-09401c1a1d8a/skitch.png)

**Comment by aquynh** [comment]
this is strange, nobody reported bugs like this before. i need to get a machine with the same setup of yours to confirm that "pip" fails.

but you should not have any issues if you compile from source. follow the docs to install all the dependencies, then build & install.

**Comment by aquynh** [comment]
i cant reproduce this on my Ubuntu 16.04.1: everything works as in https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-NIX.md

**Comment by Leeericent** [comment]
I follow the doc to  build&install, this time seems to work well. Thanks a lot.
