### ISSUE TITLE
assemble bug (mov rax,qword ptr gs:[0x60])

### ISSUE THREAD

**Issue by or75** [keystone-engine/keystone#317]
from this "mov rax,qword ptr gs:[0x60]"
to this "mov eax, gs:[0x60]"

**Comment by aquynh** [comment]
Yes confirmed.

**Comment by shareef12** [comment]
Looks to be caused by incorrect ordering of x86 instruction prefixes. Keystone emits [ 48 65 ... ] which is REX.W followed by GS segment override prefix. Changing the order of the prefixes to [ 65 48 ... ] seems to result in a correct encoding.

Per the intel x86 manual vol 2:
```
Only one REX prefix is allowed per instruction. If used, the REX prefix byte
must immediately precede the opcode byte or the escape opcode byte (0FH).
When a REX prefix is used in conjunction with an instruction containing a
mandatory prefix, the mandatory prefix must come before the REX so the
REX prefix can be immediately preceding the opcode or the escape byte.
```
