### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [keystone-engine/keystone#348]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for keystone. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by aquynh** [comment]
thanks, but do you mean tarballs for older releases, or for future releases?

**Comment by david942j** [comment]
May I know why `keystone` isn't pushed to package repositories as `capstone`?
It would be very nice if we can do `brew/apt-get install keystone` instead of compiling it.

**Comment by david942j** [comment]
Seems there's no `libkeystone.dylib` installed via brew, but I need it for bindings

**Comment by aquynh** [comment]
There should be, under /usr/local/lib

**Comment by david942j** [comment]
(sorry for not familiar with macOS)
But under `/usr/local/lib` I only found `libkeystone.a`, is that enough for bindings to work?
I tried Ruby binding and it says `Could not open library 'libkeystone.dylib': dlopen(libkeystone.dylib, 5): image not found`

**Comment by david942j** [comment]
Any update?
Also I would be glad if `keystone` can be installed via `apt`

**Comment by evandrix** [comment]
**bump**
