### ISSUE TITLE
Support for Xcode 10 beta

### ISSUE THREAD

**Issue by BinyaminSharet** [keystone-engine/keystone#365]
Xcode 10 beta does not support i386, this causes the build to fail since ARCH="i386;x86_64" in make-common.sh.
Maybe remove i386 support from OSX?

**Comment by aquynh** [comment]
How about making that default, but still leaving a choice to build fat
binary there for older Xcode? Can you make a pull req?

**Comment by BinyaminSharet** [comment]
Opened PR #366
