### ISSUE TITLE
Calling a 64-bit address

### ISSUE THREAD

**Issue by ZenLulz** [keystone-engine/keystone#417]
Hello ! I expect Keystone to be able to call a 64-bit address, for example:

    ./kstool x64 "call 0xFAA002AD0" 0

Nonetheless, this execution throws the error:

    ERROR: failed on ks_asm() with count = 1, error = 'Invalid fixup (KS_ERR_ASM_FIXUP_INVALID)' (code = 161)

I executed this on Windows and on macOS with the same result.

**Comment by AlexAltea** [comment]
You have specified 0x0 as base address and 0xFAA002AD0 as an absolute call destination address, the difference between these two cannot fit in a 32-bits operand which is the maximum allowed, see "*CALL Procedure*" in the Intel SDM Vol. 2A [1].

You have several options:
1. Move the 64-bit value to a temporary register: `./kstool x64 "mov rax, 0xFAA002AD0; call rax" 0`. Note that only MOV instructions support *imm64* operands.
2. Move the compiled code closer to the destination, which could be difficult depending on what you're trying to do. E.g.:
`./kstool x64 "call 0xFAA002AD0" 0xFAA000000`.
3. Setup some segment selector with a closer base address (again e.g.: 0xFAA000000), and make absolute calls relative to that base.

The CALL instruction is quite complex, check the manual for inspiration on how to encode it.

Feel free to close the issue though! :-)

[1] https://software.intel.com/content/dam/develop/public/us/en/documents/325383-sdm-vol-2abcd.pdf
