### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by sielicki** [keystone-engine/keystone#439]
The current release of Keystone was tagged when the most recent release of LLVM was 3.8.1! Please consider making a new tagged release.

https://github.com/keystone-engine/keystone/compare/0.9.1...master

**Comment by Mic92** [comment]
Ping?

**Comment by TheAifam5** [comment]
Same thing with rust bindings. Crate.io shows 0.9 but the Readme shows 0.10.0

**Comment by sielicki** [comment]
Preemptively closing due to today's commits. Congratulations on 0.9.2 and thank you for all the work on keystone!

**Comment by aquynh** [comment]
@TheAifam5 i made a change to modify version of Rust binding to 0.9.2: https://github.com/keystone-engine/keystone/commit/9d713d5a985c62dd95c9dd7509307a89ef4ed818. cc @nl5887 @gunyarakun 

i will tag 0.9.2 this weekend.
