### ISSUE TITLE
How to build x64 dll on windows?

### ISSUE THREAD

**Issue by iTruth** [keystone-engine/keystone#479]

**Comment by aquynh** [comment]
please see the docs, linked from README

**Comment by iTruth** [comment]
> 
> please see the docs, linked from README

Well.. I was already read [COMPILE-WINDOWS.md](https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-WINDOWS.md), but there is no such a method that can be compile 64bit dll file. 
And also I see the usage in nmake-dll.bat(:: Usage: nmake-dll.bat [x86 arm aarch64 m68k mips sparc], default build all.)
and the syntax in make-share.sh(# syntax: make-share.sh [debug] [macos-universal|macos-no-universal] [lib32] [lib_only])
It seems like we can not build x64 dll through nmake-dll.bat, If I am wrong, can you tell me the way to compile x64 dll on windows
