### ISSUE TITLE
python KsError: Invalid Operand for lea rsi, ptr [rip+0x3c1ef]

### ISSUE THREAD

**Issue by Icegrave0391** [keystone-engine/keystone#492]
Hi, 
I tried to use keystone for assembling, but an error occurred when the textual assembly instruction is:
`lea rsi, ptr [rip+0x3c1ef]`

While my arch is `KS_ARCH_X86` and mode is `KS_MODE_64`, the error is:
`keystone.keystone.KsError: Invalid operand (KS_ERR_ASM_INVALIDOPERAND)`
Does that an error?

**Comment by thejoelpatrol** [comment]
try a size directive :
`lea rsi, qword ptr [rip+0x3c1ef]`
this makes your sample assemble for me
