### ISSUE TITLE
useless 3E (ds segment override) prefix

### ISSUE THREAD

**Issue by mrexodia** [keystone-engine/keystone#9]
When assembling `JMP DWORD PTR DS:[100]` (x32 mode) it will output: `3E FF 25 64 00 00 00` (DS segment override prefix) this is also the implicit segment so the correct output should be `FF 25 64 00 00 00`

**Comment by aquynh** [comment]
all the tests passed now.

```
$ cd suite
$ ./test_xedparse.py
147/147 tests were successful!
```

**Comment by mrexodia** [comment]
Nice!
